name: Flask CI

# This workflow will run whenever code is pushed to the repository or a pull request is created
on:
  push:
    branches:
      - main

# Define the jobs that make up this workflow
jobs:
  test:
    runs-on: ubuntu-latest  # The operating system used for the runner ( Github Action is having this os for running)

    # Define the steps to be executed within this job
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3  # Check out the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the Python version to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version

      - name: Run tests
        run: |
          pytest  # Run pytest to execute the test cases

